/*********************************************************
 * irecordset.h
 * contents: IRecordSet interface for navigating records 
 * date: 2008-07-28 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef _IRECORDSET_H_
#define _IRECORDSET_H_

#include "../icsunknown.h"

//forward declarations

/*
 * 记录集操作接口：用于遍历记录集
 */
class IRecordSet : public IICSUnknown
{
public:
	//当前记录在记录集中的位置[-1表示第一条之前；－2表示最后一条之后]
	virtual int CurrentPos() = 0;
	
	//移动当前记录到指定位置。relative表示是否相对当前位置偏移。
	virtual bool Seek ( int i, bool relative = false ) = 0; 
	
	//移动到下一条记录
	virtual bool Next () = 0;
	
	//移动到前一条记录
	virtual bool Prev () = 0; 
	
	//移动到第一条记录
	virtual bool First () = 0;
	
	//移动到最后一条记录
	virtual bool Last () = 0; 	

	//记录集大小
	virtual int Size() = 0;
};

#endif