/*********************************************************
 * scadalib_alarm.h
 * contents: Ialarm interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_alarm_H_
#define SCADALIB_alarm_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Ialarmclass;
class Ialarmlevel;

class Ialarm : public IRecordSet
{
public:
	//associations
	virtual Ialarmclass* Relevantalarmclass() = 0;

	virtual Ialarmlevel* Relevantalarmlevel() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getalarmlevelid() = 0;

	virtual void Setalarmlevelid(int alarmlevelid) = 0;

	virtual int Getalarmclassid() = 0;

	virtual void Setalarmclassid(int alarmclassid) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual string_type Getalarmformat() = 0;

	virtual void Setalarmformat(const char* alarmformat) = 0;

	virtual int Getautoconfirmtime() = 0;

	virtual void Setautoconfirmtime(int autoconfirmtime) = 0;

	virtual int Getvoicealarmtimes() = 0;

	virtual void Setvoicealarmtimes(int voicealarmtimes) = 0;

	virtual int Getpriority() = 0;

	virtual void Setpriority(int priority) = 0;

	virtual string_type Getfamily() = 0;

	virtual void Setfamily(const char* family) = 0;

	virtual int Getalmopt() = 0;

	virtual void Setalmopt(int almopt) = 0;

	virtual int Getuserdefineflag() = 0;

	virtual void Setuserdefineflag(int userdefineflag) = 0;

	virtual string_type Getalarmpage() = 0;

	virtual void Setalarmpage(const char* alarmpage) = 0;

	virtual string_type Getalarmvoice() = 0;

	virtual void Setalarmvoice(const char* alarmvoice) = 0;


};

#endif