/*********************************************************
 * scadalib_ctrlvaltype.h
 * contents: Ictrlvaltype interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_ctrlvaltype_H_
#define SCADALIB_ctrlvaltype_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Imeastype;
class Ialarm;

class Ictrlvaltype : public IRecordSet
{
public:
	//associations
	virtual Imeastype* Relevantmeastype() = 0;

	virtual Ialarm* Relevantalarm() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getalarmid() = 0;

	virtual void Setalarmid(int alarmid) = 0;

	virtual int Getmeastypeid() = 0;

	virtual void Setmeastypeid(int meastypeid) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getvalue() = 0;

	virtual void Setvalue(int value) = 0;

	virtual string_type Getctrlcode() = 0;

	virtual void Setctrlcode(const char* ctrlcode) = 0;

	virtual int Getjudgeaimval() = 0;

	virtual void Setjudgeaimval(int judgeaimval) = 0;

	virtual int Getaimval() = 0;

	virtual void Setaimval(int aimval) = 0;


};

#endif