/*********************************************************
 * scadalib_msgemail.h
 * contents: Imsgemail interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_msgemail_H_
#define SCADALIB_msgemail_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"



class Imsgemail : public IRecordSet
{
public:
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getemailuser() = 0;

	virtual void Setemailuser(const char* emailuser) = 0;

	virtual string_type Getemailaddress() = 0;

	virtual void Setemailaddress(const char* emailaddress) = 0;


};

#endif