/*********************************************************
 * scadalib_toposystem.h
 * contents: Itoposystem interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_toposystem_H_
#define SCADALIB_toposystem_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"



class Itoposystem : public IRecordSet
{
public:
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getequipmentsum() = 0;

	virtual void Setequipmentsum(int equipmentsum) = 0;

	virtual int Getterminalsum() = 0;

	virtual void Setterminalsum(int terminalsum) = 0;

	virtual int Getconnnodesum() = 0;

	virtual void Setconnnodesum(int connnodesum) = 0;

	virtual int Getneednodesum() = 0;

	virtual void Setneednodesum(int neednodesum) = 0;

	virtual int Getneedpowersum() = 0;

	virtual void Setneedpowersum(int needpowersum) = 0;

	virtual int Getneedloadsum() = 0;

	virtual void Setneedloadsum(int needloadsum) = 0;

	virtual int Gettoponodesum() = 0;

	virtual void Settoponodesum(int toponodesum) = 0;

	virtual int Gettopolinesum() = 0;

	virtual void Settopolinesum(int topolinesum) = 0;

	virtual int Gettopoislandsum() = 0;

	virtual void Settopoislandsum(int topoislandsum) = 0;

	virtual int Getactiveislands() = 0;

	virtual void Setactiveislands(int activeislands) = 0;


};

#endif