/*********************************************************
 * scadalib_topoequip.h
 * contents: Itopoequip interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_topoequip_H_
#define SCADALIB_topoequip_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Itopoisland;
class Istatus;
class Iequipment;

class Itopoequip : public IRecordSet
{
public:
	//associations
	virtual Itopoisland* Relevanttopoisland() = 0;

	virtual Istatus* Relevantstatus() = 0;

	virtual Iequipment* Relevant() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Gettopoislandid() = 0;

	virtual void Settopoislandid(int topoislandid) = 0;

	virtual int Getterminalsum() = 0;

	virtual void Setterminalsum(int terminalsum) = 0;

	virtual int Getbodyflag() = 0;

	virtual void Setbodyflag(int bodyflag) = 0;

	virtual int Getconnectflag() = 0;

	virtual void Setconnectflag(int connectflag) = 0;

	virtual int Getshapenum() = 0;

	virtual void Setshapenum(int shapenum) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Getstatusid() = 0;

	virtual void Setstatusid(int statusid) = 0;


};

#endif