/*********************************************************
 * scadalib_defines.h
 * contents: definitions of common defines
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_DEFINES_H_
#define SCADALIB_DEFINES_H_

#define MODULE_SCADALIB "scadalib"
#define IID_ISCADAOBJFACTORY	"IScadaObjFactory"
#define CLSID_ISCADAOBJFACTORY	"9A101586-DA3D-44cd-9BF4-5726FB70AB37"

#define HEAVYBLOCKSIZE	20480
#define BIGBLOCKSIZE	2048
#define SBLOCKSIZE	1024
#define REGBUFF	256
#define SBUFF	64
#define TINYBUFF	32

#define IID_IRecordSet "IRecordSet"
#define IID_Iabrupttype	"Iabrupttype"
#define IID_Iaccumcalmap	"Iaccumcalmap"
#define IID_Iaccumulator	"Iaccumulator"
#define IID_Iaccumulsrc	"Iaccumulsrc"
#define IID_Iacperiodstat	"Iacperiodstat"
#define IID_Iacurvelimit	"Iacurvelimit"
#define IID_Ialarm	"Ialarm"
#define IID_Ialarmclass	"Ialarmclass"
#define IID_Ialarmemail	"Ialarmemail"
#define IID_Ialarmgroup	"Ialarmgroup"
#define IID_Ialarmlevel	"Ialarmlevel"
#define IID_Ialarmpara	"Ialarmpara"
#define IID_Ialarmphone	"Ialarmphone"
#define IID_Ialimittype	"Ialimittype"
#define IID_Ialmgrptype	"Ialmgrptype"
#define IID_Ianalog	"Ianalog"
#define IID_Ianalogcalmap	"Ianalogcalmap"
#define IID_Ianalogsrc	"Ianalogsrc"
#define IID_Ianalogstat	"Ianalogstat"
#define IID_Ianalprdlmt	"Ianalprdlmt"
#define IID_Iaperiodstat	"Iaperiodstat"
#define IID_Iapp	"Iapp"
#define IID_Ibay	"Ibay"
#define IID_Ibayarea	"Ibayarea"
#define IID_Ibaytype	"Ibaytype"
#define IID_Icalvaluetype	"Icalvaluetype"
#define IID_Icontrol	"Icontrol"
#define IID_Icsfcommsrc	"Icsfcommsrc"
#define IID_Ictrlexp	"Ictrlexp"
#define IID_Ictrlvaltype	"Ictrlvaltype"
#define IID_Ictrlworddef	"Ictrlworddef"
#define IID_Idataclass	"Idataclass"
#define IID_Idistrict	"Idistrict"
#define IID_Iequipclass	"Iequipclass"
#define IID_Iequipment	"Iequipment"
#define IID_Iequiptype	"Iequiptype"
#define IID_Iexprcal	"Iexprcal"
#define IID_Ifamily	"Ifamily"
#define IID_Imeasclass	"Imeasclass"
#define IID_Imeastype	"Imeastype"
#define IID_Imeasunit	"Imeasunit"
#define IID_Imsgemail	"Imsgemail"
#define IID_Imsgphone	"Imsgphone"
#define IID_Iperiod	"Iperiod"
#define IID_Iperiodtype	"Iperiodtype"
#define IID_Isetting	"Isetting"
#define IID_Isettingarea	"Isettingarea"
#define IID_Isettingenum	"Isettingenum"
#define IID_Isoe	"Isoe"
#define IID_Isperiodstat	"Isperiodstat"
#define IID_Istation	"Istation"
#define IID_Istationarea	"Istationarea"
#define IID_Istationtype	"Istationtype"
#define IID_Istatus	"Istatus"
#define IID_Istatuscalmap	"Istatuscalmap"
#define IID_Istatussrc	"Istatussrc"
#define IID_Istatusstat	"Istatusstat"
#define IID_Istvaltype	"Istvaltype"
#define IID_Itagtype	"Itagtype"
#define IID_Itimertype	"Itimertype"
#define IID_Itopoconnnode	"Itopoconnnode"
#define IID_Itopoequip	"Itopoequip"
#define IID_Itopoisland	"Itopoisland"
#define IID_Itopoline	"Itopoline"
#define IID_Itoponode	"Itoponode"
#define IID_Itoposystem	"Itoposystem"
#define IID_Itopoterminal	"Itopoterminal"
#define IID_Ivoltage	"Ivoltage"


#endif