/*********************************************************
 * scadalib_equipment.h
 * contents: Iequipment interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_equipment_H_
#define SCADALIB_equipment_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Ibay;
class Iequipment;
class Iequiptype;
class Iequipment;
class Itagtype;
class Ivoltage;
class Istatus;
class Iequipclass;

class Iequipment : public IRecordSet
{
public:
	//associations
	virtual Ibay* Relevantbay() = 0;

	virtual Iequipment* Relevantspanbayequip() = 0;

	virtual Iequiptype* Relevantequiptype() = 0;

	virtual Iequipment* Relevantsupequip() = 0;

	virtual Itagtype* Relevanttagtype() = 0;

	virtual Ivoltage* Relevantvoltage() = 0;

	virtual Istatus* Relevantstatus() = 0;

	virtual Iequipclass* Relevantequipclass() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getbayid() = 0;

	virtual void Setbayid(int bayid) = 0;

	virtual int Getequiptypeid() = 0;

	virtual void Setequiptypeid(int equiptypeid) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;

	virtual string_type Getpathname() = 0;

	virtual void Setpathname(const char* pathname) = 0;

	virtual int Getstatusid() = 0;

	virtual void Setstatusid(int statusid) = 0;

	virtual int Getistag() = 0;

	virtual void Setistag(int istag) = 0;

	virtual int Gettagtypeid() = 0;

	virtual void Settagtypeid(int tagtypeid) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Getisspanbay() = 0;

	virtual void Setisspanbay(int isspanbay) = 0;

	virtual int Getspanbayequipid() = 0;

	virtual void Setspanbayequipid(int spanbayequipid) = 0;

	virtual int Getvoltageid() = 0;

	virtual void Setvoltageid(int voltageid) = 0;

	virtual int Getsupequipid() = 0;

	virtual void Setsupequipid(int supequipid) = 0;

	virtual int Getdoublesatus() = 0;

	virtual void Setdoublesatus(int doublesatus) = 0;

	virtual int Getdpsdelay() = 0;

	virtual void Setdpsdelay(int dpsdelay) = 0;

	virtual int Getcommid() = 0;

	virtual void Setcommid(int commid) = 0;

	virtual string_type Getfamily() = 0;

	virtual void Setfamily(const char* family) = 0;

	virtual int Getstationid() = 0;

	virtual void Setstationid(int stationid) = 0;

	virtual int Getequipclassid() = 0;

	virtual void Setequipclassid(int equipclassid) = 0;

	virtual int Getlockenable() = 0;

	virtual void Setlockenable(int lockenable) = 0;


};

#endif