/*********************************************************
 * scadalib_msgphone.h
 * contents: Imsgphone interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_msgphone_H_
#define SCADALIB_msgphone_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"



class Imsgphone : public IRecordSet
{
public:
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getphoneuser() = 0;

	virtual void Setphoneuser(const char* phoneuser) = 0;

	virtual string_type Getphonenum() = 0;

	virtual void Setphonenum(const char* phonenum) = 0;


};

#endif