/*********************************************************
 * scadalib_timertype.h
 * contents: Itimertype interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_timertype_H_
#define SCADALIB_timertype_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"



class Itimertype : public IRecordSet
{
public:
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getcycmode() = 0;

	virtual void Setcycmode(int cycmode) = 0;

	virtual int Getcycspan() = 0;

	virtual void Setcycspan(int cycspan) = 0;

	virtual dt_type Getstarttime() = 0;

	virtual void Setstarttime(dt_type starttime) = 0;


};

#endif