/*********************************************************
 * scadalib_topoconnnode.h
 * contents: Itopoconnnode interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_topoconnnode_H_
#define SCADALIB_topoconnnode_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Itoponode;
class Itopoisland;

class Itopoconnnode : public IRecordSet
{
public:
	//associations
	virtual Itoponode* Relevanttoponode() = 0;

	virtual Itopoisland* Relevanttopoisland() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Gettopoislandid() = 0;

	virtual void Settopoislandid(int topoislandid) = 0;

	virtual int Gettoponodeid() = 0;

	virtual void Settoponodeid(int toponodeid) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getterminalsum() = 0;

	virtual void Setterminalsum(int terminalsum) = 0;


};

#endif