/*********************************************************
 * scadalib_acperiodstat.h
 * contents: Iacperiodstat interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_acperiodstat_H_
#define SCADALIB_acperiodstat_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Iperiodtype;
class Iaccumulator;

class Iacperiodstat : public IRecordSet
{
public:
	//associations
	virtual Iperiodtype* Relevantperiodtype() = 0;

	virtual Iaccumulator* Relevantaccumulator() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getaccumulatorid() = 0;

	virtual void Setaccumulatorid(int accumulatorid) = 0;

	virtual int Getperiodtypeid() = 0;

	virtual void Setperiodtypeid(int periodtypeid) = 0;

	virtual double Getamountvalue() = 0;

	virtual void Setamountvalue(double amountvalue) = 0;

	virtual dt_type Getstatictime() = 0;

	virtual void Setstatictime(dt_type statictime) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Getsaveflag() = 0;

	virtual void Setsaveflag(int saveflag) = 0;


};

#endif