/*********************************************************
 * scadalib_analog.h
 * contents: Ianalog interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_analog_H_
#define SCADALIB_analog_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Iabrupttype;
class Itimertype;
class Iequipment;
class Imeasunit;
class Ialimittype;
class Imeastype;
class Imeasclass;
class Icsfcommsrc;

class Ianalog : public IRecordSet
{
public:
	//associations
	virtual Iabrupttype* Relevantabrupttype() = 0;

	virtual Itimertype* Relevantseqsvtimer() = 0;

	virtual Iequipment* Relevantequip() = 0;

	virtual Imeasunit* Relevantmeasunit() = 0;

	virtual Ialimittype* Relevantlimittype() = 0;

	virtual Imeastype* Relevantmeastype() = 0;

	virtual Imeasclass* Relevantmeasclass() = 0;

	virtual Icsfcommsrc* Relevantcommsrc() = 0;

	//
	virtual int Getuselmttypeflag() = 0;

	virtual void Setuselmttypeflag(int uselmttypeflag) = 0;

	virtual double Getuppervalue() = 0;

	virtual void Setuppervalue(double uppervalue) = 0;

	virtual double Getlowervalue() = 0;

	virtual void Setlowervalue(double lowervalue) = 0;

	virtual int Getupperalarmact() = 0;

	virtual void Setupperalarmact(int upperalarmact) = 0;

	virtual int Getloweralarmact() = 0;

	virtual void Setloweralarmact(int loweralarmact) = 0;

	virtual double Getdeadzone() = 0;

	virtual void Setdeadzone(double deadzone) = 0;

	virtual int Getdelaytime() = 0;

	virtual void Setdelaytime(int delaytime) = 0;

	virtual int Getstationid() = 0;

	virtual void Setstationid(int stationid) = 0;

	virtual int Getbayid() = 0;

	virtual void Setbayid(int bayid) = 0;

	virtual int Getmeasclassid() = 0;

	virtual void Setmeasclassid(int measclassid) = 0;

	virtual int Getdatatransflag() = 0;

	virtual void Setdatatransflag(int datatransflag) = 0;

	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getequipid() = 0;

	virtual void Setequipid(int equipid) = 0;

	virtual int Getseqsvtimerid() = 0;

	virtual void Setseqsvtimerid(int seqsvtimerid) = 0;

	virtual int Getmeastypeid() = 0;

	virtual void Setmeastypeid(int meastypeid) = 0;

	virtual int Getlimittypeid() = 0;

	virtual void Setlimittypeid(int limittypeid) = 0;

	virtual int Getabrupttypeid() = 0;

	virtual void Setabrupttypeid(int abrupttypeid) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;

	virtual string_type Getpathname() = 0;

	virtual void Setpathname(const char* pathname) = 0;

	virtual double Getscalefactor() = 0;

	virtual void Setscalefactor(double scalefactor) = 0;

	virtual double Getoffset() = 0;

	virtual void Setoffset(double offset) = 0;

	virtual double Getzerodb() = 0;

	virtual void Setzerodb(double zerodb) = 0;

	virtual double Getdiffdb() = 0;

	virtual void Setdiffdb(double diffdb) = 0;

	virtual int Getolddatimelim() = 0;

	virtual void Setolddatimelim(int olddatimelim) = 0;

	virtual int Getmeasunitid() = 0;

	virtual void Setmeasunitid(int measunitid) = 0;

	virtual int Getsmprate() = 0;

	virtual void Setsmprate(int smprate) = 0;

	virtual double Getmaxval() = 0;

	virtual void Setmaxval(double maxval) = 0;

	virtual double Getminval() = 0;

	virtual void Setminval(double minval) = 0;

	virtual double Getqualifyupval() = 0;

	virtual void Setqualifyupval(double qualifyupval) = 0;

	virtual double Getqualifyloval() = 0;

	virtual void Setqualifyloval(double qualifyloval) = 0;

	virtual double Getqualifydb() = 0;

	virtual void Setqualifydb(double qualifydb) = 0;

	virtual string_type Getalarmpage() = 0;

	virtual void Setalarmpage(const char* alarmpage) = 0;

	virtual string_type Getalarmvoice() = 0;

	virtual void Setalarmvoice(const char* alarmvoice) = 0;

	virtual int Getcommsrcid() = 0;

	virtual void Setcommsrcid(int commsrcid) = 0;

	virtual int Getcommpointid() = 0;

	virtual void Setcommpointid(int commpointid) = 0;

	virtual int Getcomplexflag() = 0;

	virtual void Setcomplexflag(int complexflag) = 0;

	virtual int Getproflag() = 0;

	virtual void Setproflag(int proflag) = 0;

	virtual double Getrawvalue() = 0;

	virtual void Setrawvalue(double rawvalue) = 0;

	virtual int Getquality() = 0;

	virtual void Setquality(int quality) = 0;

	virtual int Getorigin() = 0;

	virtual void Setorigin(int origin) = 0;

	virtual dt_type Getcurdatatime() = 0;

	virtual void Setcurdatatime(dt_type curdatatime) = 0;

	virtual double Getcalvalue() = 0;

	virtual void Setcalvalue(double calvalue) = 0;

	virtual double Getangle() = 0;

	virtual void Setangle(double angle) = 0;

	virtual int Getprealarmstate() = 0;

	virtual void Setprealarmstate(int prealarmstate) = 0;

	virtual int Getexceptime1() = 0;

	virtual void Setexceptime1(int exceptime1) = 0;

	virtual int Getexceptime2() = 0;

	virtual void Setexceptime2(int exceptime2) = 0;

	virtual int Getunchangedtime() = 0;

	virtual void Setunchangedtime(int unchangedtime) = 0;

	virtual int Getisabrupt() = 0;

	virtual void Setisabrupt(int isabrupt) = 0;

	virtual int Getabrupttime() = 0;

	virtual void Setabrupttime(int abrupttime) = 0;

	virtual int Getoperatorstate() = 0;

	virtual void Setoperatorstate(int operatorstate) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Getlockflag() = 0;

	virtual void Setlockflag(int lockflag) = 0;

	virtual string_type Getfamily() = 0;

	virtual void Setfamily(const char* family) = 0;


};

#endif