/*********************************************************
 * scadalib_status.h
 * contents: Istatus interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_status_H_
#define SCADALIB_status_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Itimertype;
class Icsfcommsrc;
class Imeastype;
class Iequipment;
class Imeasclass;

class Istatus : public IRecordSet
{
public:
	//associations
	virtual Itimertype* Relevantseqsvtimer() = 0;

	virtual Icsfcommsrc* Relevantcommsrc() = 0;

	virtual Imeastype* Relevantmeastype() = 0;

	virtual Iequipment* Relevantequip() = 0;

	virtual Imeasclass* Relevantmeasclass() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getequipid() = 0;

	virtual void Setequipid(int equipid) = 0;

	virtual int Getseqsvtimerid() = 0;

	virtual void Setseqsvtimerid(int seqsvtimerid) = 0;

	virtual int Getmeastypeid() = 0;

	virtual void Setmeastypeid(int meastypeid) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;

	virtual string_type Getpathname() = 0;

	virtual void Setpathname(const char* pathname) = 0;

	virtual string_type Getalarmpage() = 0;

	virtual void Setalarmpage(const char* alarmpage) = 0;

	virtual string_type Getalarmvoice() = 0;

	virtual void Setalarmvoice(const char* alarmvoice) = 0;

	virtual int Getproflag() = 0;

	virtual void Setproflag(int proflag) = 0;

	virtual int Getcommsrcid() = 0;

	virtual void Setcommsrcid(int commsrcid) = 0;

	virtual int Getcommpointid() = 0;

	virtual void Setcommpointid(int commpointid) = 0;

	virtual int Getlastvalue() = 0;

	virtual void Setlastvalue(int lastvalue) = 0;

	virtual int Getcurvalue() = 0;

	virtual void Setcurvalue(int curvalue) = 0;

	virtual int Getgzstate() = 0;

	virtual void Setgzstate(int gzstate) = 0;

	virtual int Getquality() = 0;

	virtual void Setquality(int quality) = 0;

	virtual int Getorigin() = 0;

	virtual void Setorigin(int origin) = 0;

	virtual dt_type Getcurdatatime() = 0;

	virtual void Setcurdatatime(dt_type curdatatime) = 0;

	virtual int Getrawvalue() = 0;

	virtual void Setrawvalue(int rawvalue) = 0;

	virtual dt_type Getrawvaluetime() = 0;

	virtual void Setrawvaluetime(dt_type rawvaluetime) = 0;

	virtual int Getsurgetimes() = 0;

	virtual void Setsurgetimes(int surgetimes) = 0;

	virtual int Getalarmcounter() = 0;

	virtual void Setalarmcounter(int alarmcounter) = 0;

	virtual int Getfaulttripcount() = 0;

	virtual void Setfaulttripcount(int faulttripcount) = 0;

	virtual int Getoperatorstate() = 0;

	virtual void Setoperatorstate(int operatorstate) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual string_type Getfamily() = 0;

	virtual void Setfamily(const char* family) = 0;

	virtual int Getlockflag() = 0;

	virtual void Setlockflag(int lockflag) = 0;

	virtual int Getdelaytime() = 0;

	virtual void Setdelaytime(int delaytime) = 0;

	virtual int Getrevertlmt() = 0;

	virtual void Setrevertlmt(int revertlmt) = 0;

	virtual int Getmaxfaultlmt() = 0;

	virtual void Setmaxfaultlmt(int maxfaultlmt) = 0;

	virtual int Getchangecountlmt() = 0;

	virtual void Setchangecountlmt(int changecountlmt) = 0;

	virtual int Getrevertalarmact() = 0;

	virtual void Setrevertalarmact(int revertalarmact) = 0;

	virtual int Getmaxfaultalact() = 0;

	virtual void Setmaxfaultalact(int maxfaultalact) = 0;

	virtual int Getchangecountalact() = 0;

	virtual void Setchangecountalact(int changecountalact) = 0;

	virtual int Getstationid() = 0;

	virtual void Setstationid(int stationid) = 0;

	virtual int Getbayid() = 0;

	virtual void Setbayid(int bayid) = 0;

	virtual int Getmeasclassid() = 0;

	virtual void Setmeasclassid(int measclassid) = 0;

	virtual int Getdatatransflag() = 0;

	virtual void Setdatatransflag(int datatransflag) = 0;


};

#endif