/*********************************************************
 * scadalib_aperiodstat.h
 * contents: Iaperiodstat interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_aperiodstat_H_
#define SCADALIB_aperiodstat_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Ianalogstat;
class Iperiodtype;

class Iaperiodstat : public IRecordSet
{
public:
	//associations
	virtual Ianalogstat* Relevantanalog() = 0;

	virtual Iperiodtype* Relevantperiodtype() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getanalogid() = 0;

	virtual void Setanalogid(int analogid) = 0;

	virtual int Getperiodtypeid() = 0;

	virtual void Setperiodtypeid(int periodtypeid) = 0;

	virtual dt_type Getstatictime() = 0;

	virtual void Setstatictime(dt_type statictime) = 0;

	virtual int Gettotaltime() = 0;

	virtual void Settotaltime(int totaltime) = 0;

	virtual int Getqualifytime() = 0;

	virtual void Setqualifytime(int qualifytime) = 0;

	virtual int Getllowertime() = 0;

	virtual void Setllowertime(int llowertime) = 0;

	virtual int Getllowercount() = 0;

	virtual void Setllowercount(int llowercount) = 0;

	virtual int Getlowertime() = 0;

	virtual void Setlowertime(int lowertime) = 0;

	virtual int Getlowercount() = 0;

	virtual void Setlowercount(int lowercount) = 0;

	virtual int Getuppertime() = 0;

	virtual void Setuppertime(int uppertime) = 0;

	virtual int Getuppercount() = 0;

	virtual void Setuppercount(int uppercount) = 0;

	virtual int Getuupertime() = 0;

	virtual void Setuupertime(int uupertime) = 0;

	virtual int Getuupercount() = 0;

	virtual void Setuupercount(int uupercount) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Getsaveflag() = 0;

	virtual void Setsaveflag(int saveflag) = 0;


};

#endif