/*********************************************************
 * scadalib_stvaltype.h
 * contents: Istvaltype interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_stvaltype_H_
#define SCADALIB_stvaltype_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Imeastype;

class Istvaltype : public IRecordSet
{
public:
	//associations
	virtual Imeastype* Relevantmeastype() = 0;

	//
	virtual int Getfaultalarmid() = 0;

	virtual void Setfaultalarmid(int faultalarmid) = 0;

	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getmeastypeid() = 0;

	virtual void Setmeastypeid(int meastypeid) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getvalue() = 0;

	virtual void Setvalue(int value) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;

	virtual int Getctrlalarmid() = 0;

	virtual void Setctrlalarmid(int ctrlalarmid) = 0;


};

#endif