/*********************************************************
 * scadalib_equiptype.h
 * contents: Iequiptype interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_equiptype_H_
#define SCADALIB_equiptype_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Iequipclass;

class Iequiptype : public IRecordSet
{
public:
	//associations
	virtual Iequipclass* Relevantequipclass() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getequipclassid() = 0;

	virtual void Setequipclassid(int equipclassid) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual int Getdoublesatus() = 0;

	virtual void Setdoublesatus(int doublesatus) = 0;

	virtual int Getdpsdelay() = 0;

	virtual void Setdpsdelay(int dpsdelay) = 0;


};

#endif