/*********************************************************
 * scadalib_equipclass.h
 * contents: Iequipclass interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_equipclass_H_
#define SCADALIB_equipclass_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Ibaytype;

class Iequipclass : public IRecordSet
{
public:
	//associations
	virtual Ibaytype* Relevantbaytype() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getcreatebayflag() = 0;

	virtual void Setcreatebayflag(int createbayflag) = 0;

	virtual int Getbaytypeid() = 0;

	virtual void Setbaytypeid(int baytypeid) = 0;


};

#endif