/*********************************************************
 * scadalib_stationarea.h
 * contents: Istationarea interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_stationarea_H_
#define SCADALIB_stationarea_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Istation;

class Istationarea : public IRecordSet
{
public:
	//associations
	virtual Istation* Relevantstation() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getstationid() = 0;

	virtual void Setstationid(int stationid) = 0;

	virtual string_type Getareaid() = 0;

	virtual void Setareaid(const char* areaid) = 0;


};

#endif