/*********************************************************
 * scadalib_setting.h
 * contents: Isetting interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_setting_H_
#define SCADALIB_setting_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Imeasclass;
class Imeastype;
class Icsfcommsrc;
class Imeasunit;
class Ictrlworddef;
class Ianalog;
class Isettingenum;
class Iequipment;

class Isetting : public IRecordSet
{
public:
	//associations
	virtual Imeasclass* Relevantmeasclass() = 0;

	virtual Imeastype* Relevantmeastype() = 0;

	virtual Icsfcommsrc* Relevantcommsrc() = 0;

	virtual Imeasunit* Relevantmeasunit() = 0;

	virtual Ictrlworddef* Relevantctrlworddef() = 0;

	virtual Ianalog* Relevantanalog() = 0;

	virtual Isettingenum* Relevantsettingenum() = 0;

	virtual Iequipment* Relevantequip() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getequipid() = 0;

	virtual void Setequipid(int equipid) = 0;

	virtual int Getanalogid() = 0;

	virtual void Setanalogid(int analogid) = 0;

	virtual int Getsettingenumid() = 0;

	virtual void Setsettingenumid(int settingenumid) = 0;

	virtual int Getctrlworddefid() = 0;

	virtual void Setctrlworddefid(int ctrlworddefid) = 0;

	virtual int Getmeastypeid() = 0;

	virtual void Setmeastypeid(int meastypeid) = 0;

	virtual int Getcommsrcid() = 0;

	virtual void Setcommsrcid(int commsrcid) = 0;

	virtual int Getcommpointid() = 0;

	virtual void Setcommpointid(int commpointid) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getsettingmode() = 0;

	virtual void Setsettingmode(int settingmode) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;

	virtual string_type Getpathname() = 0;

	virtual void Setpathname(const char* pathname) = 0;

	virtual double Getmaxvalue() = 0;

	virtual void Setmaxvalue(double maxvalue) = 0;

	virtual double Getminvalue() = 0;

	virtual void Setminvalue(double minvalue) = 0;

	virtual double Getstep() = 0;

	virtual void Setstep(double step) = 0;

	virtual int Getmeasunitid() = 0;

	virtual void Setmeasunitid(int measunitid) = 0;

	virtual string_type Getsettingvalue() = 0;

	virtual void Setsettingvalue(const char* settingvalue) = 0;

	virtual int Getsettingarea() = 0;

	virtual void Setsettingarea(int settingarea) = 0;

	virtual int Geteditarea() = 0;

	virtual void Seteditarea(int editarea) = 0;

	virtual int Getsetareanum() = 0;

	virtual void Setsetareanum(int setareanum) = 0;

	virtual int Getvaluetype() = 0;

	virtual void Setvaluetype(int valuetype) = 0;

	virtual double Getfirstcol() = 0;

	virtual void Setfirstcol(double firstcol) = 0;

	virtual double Getsecondcol() = 0;

	virtual void Setsecondcol(double secondcol) = 0;

	virtual int Getovertimelmt() = 0;

	virtual void Setovertimelmt(int overtimelmt) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual string_type Getfamily() = 0;

	virtual void Setfamily(const char* family) = 0;

	virtual int Getlockflag() = 0;

	virtual void Setlockflag(int lockflag) = 0;

	virtual int Getstationid() = 0;

	virtual void Setstationid(int stationid) = 0;

	virtual int Getbayid() = 0;

	virtual void Setbayid(int bayid) = 0;

	virtual int Getmeasclassid() = 0;

	virtual void Setmeasclassid(int measclassid) = 0;


};

#endif