/*********************************************************
 * scadalib_ctrlworddef.h
 * contents: Ictrlworddef interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_ctrlworddef_H_
#define SCADALIB_ctrlworddef_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"



class Ictrlworddef : public IRecordSet
{
public:
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;

	virtual string_type Getbitmeanings() = 0;

	virtual void Setbitmeanings(const char* bitmeanings) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;


};

#endif