/*********************************************************
 * scadalib_speriodstat.h
 * contents: Isperiodstat interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_speriodstat_H_
#define SCADALIB_speriodstat_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Iperiodtype;
class Istatusstat;

class Isperiodstat : public IRecordSet
{
public:
	//associations
	virtual Iperiodtype* Relevantperiodtype() = 0;

	virtual Istatusstat* Relevantstatus() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getstatusid() = 0;

	virtual void Setstatusid(int statusid) = 0;

	virtual int Getperiodtypeid() = 0;

	virtual void Setperiodtypeid(int periodtypeid) = 0;

	virtual int Getclosecount() = 0;

	virtual void Setclosecount(int closecount) = 0;

	virtual int Getopencount() = 0;

	virtual void Setopencount(int opencount) = 0;

	virtual int Getclosetime() = 0;

	virtual void Setclosetime(int closetime) = 0;

	virtual int Getopentime() = 0;

	virtual void Setopentime(int opentime) = 0;

	virtual int Gettotalruntime() = 0;

	virtual void Settotalruntime(int totalruntime) = 0;

	virtual int Getstaticstate() = 0;

	virtual void Setstaticstate(int staticstate) = 0;

	virtual dt_type Getstatictime() = 0;

	virtual void Setstatictime(dt_type statictime) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Gettotaltime() = 0;

	virtual void Settotaltime(int totaltime) = 0;

	virtual int Getsaveflag() = 0;

	virtual void Setsaveflag(int saveflag) = 0;


};

#endif