/*********************************************************
 * scadalib_abrupttype.h
 * contents: Iabrupttype interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_abrupttype_H_
#define SCADALIB_abrupttype_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"



class Iabrupttype : public IRecordSet
{
public:
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getisdiff() = 0;

	virtual void Setisdiff(int isdiff) = 0;

	virtual int Gettrend() = 0;

	virtual void Settrend(int trend) = 0;

	virtual double Getuplimit() = 0;

	virtual void Setuplimit(double uplimit) = 0;

	virtual double Getdownlimit() = 0;

	virtual void Setdownlimit(double downlimit) = 0;

	virtual double Getgradevalue() = 0;

	virtual void Setgradevalue(double gradevalue) = 0;

	virtual int Getgradetimelmt() = 0;

	virtual void Setgradetimelmt(int gradetimelmt) = 0;

	virtual int Getalarmlmt() = 0;

	virtual void Setalarmlmt(int alarmlmt) = 0;

	virtual int Getdelaytime() = 0;

	virtual void Setdelaytime(int delaytime) = 0;

	virtual int Getisfault() = 0;

	virtual void Setisfault(int isfault) = 0;

	virtual int Getalarmact() = 0;

	virtual void Setalarmact(int alarmact) = 0;


};

#endif