/*********************************************************
 * scadalib_analogstat.h
 * contents: Ianalogstat interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_analogstat_H_
#define SCADALIB_analogstat_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Itimertype;
class Ianalog;

class Ianalogstat : public IRecordSet
{
public:
	//associations
	virtual Itimertype* Relevantstatsvtimer() = 0;

	virtual Ianalog* Relevant() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getstatsvtimerid() = 0;

	virtual void Setstatsvtimerid(int statsvtimerid) = 0;

	virtual int Getaddtimes() = 0;

	virtual void Setaddtimes(int addtimes) = 0;

	virtual double Getaddvalue() = 0;

	virtual void Setaddvalue(double addvalue) = 0;

	virtual double Getavevalue() = 0;

	virtual void Setavevalue(double avevalue) = 0;

	virtual double Getmaxdata() = 0;

	virtual void Setmaxdata(double maxdata) = 0;

	virtual dt_type Getmaxdatatime() = 0;

	virtual void Setmaxdatatime(dt_type maxdatatime) = 0;

	virtual double Getmindata() = 0;

	virtual void Setmindata(double mindata) = 0;

	virtual dt_type Getmindatatime() = 0;

	virtual void Setmindatatime(dt_type mindatatime) = 0;

	virtual int Getuupercount() = 0;

	virtual void Setuupercount(int uupercount) = 0;

	virtual int Getuupertime() = 0;

	virtual void Setuupertime(int uupertime) = 0;

	virtual int Getuppercount() = 0;

	virtual void Setuppercount(int uppercount) = 0;

	virtual int Getuppertime() = 0;

	virtual void Setuppertime(int uppertime) = 0;

	virtual int Getlowercount() = 0;

	virtual void Setlowercount(int lowercount) = 0;

	virtual int Getlowertime() = 0;

	virtual void Setlowertime(int lowertime) = 0;

	virtual int Getllowercount() = 0;

	virtual void Setllowercount(int llowercount) = 0;

	virtual int Getllowertime() = 0;

	virtual void Setllowertime(int llowertime) = 0;

	virtual int Getqualifytime() = 0;

	virtual void Setqualifytime(int qualifytime) = 0;

	virtual dt_type Getstatictime() = 0;

	virtual void Setstatictime(dt_type statictime) = 0;

	virtual int Gettotaltime() = 0;

	virtual void Settotaltime(int totaltime) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Getsaveflag() = 0;

	virtual void Setsaveflag(int saveflag) = 0;


};

#endif