/*********************************************************
 * scadalib_soe.h
 * contents: Isoe interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_soe_H_
#define SCADALIB_soe_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Icsfcommsrc;
class Imeastype;
class Imeasclass;

class Isoe : public IRecordSet
{
public:
	//associations
	virtual Icsfcommsrc* Relevantcommsrc() = 0;

	virtual Imeastype* Relevantmeastype() = 0;

	virtual Imeasclass* Relevantmeasclass() = 0;

	//
	virtual int Getoperatorstate() = 0;

	virtual void Setoperatorstate(int operatorstate) = 0;

	virtual int Getcurvalue() = 0;

	virtual void Setcurvalue(int curvalue) = 0;

	virtual dt_type Getcurdatatime() = 0;

	virtual void Setcurdatatime(dt_type curdatatime) = 0;

	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getmeastypeid() = 0;

	virtual void Setmeastypeid(int meastypeid) = 0;

	virtual int Getcommsrcid() = 0;

	virtual void Setcommsrcid(int commsrcid) = 0;

	virtual int Getcommpointid() = 0;

	virtual void Setcommpointid(int commpointid) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;

	virtual string_type Getfamily() = 0;

	virtual void Setfamily(const char* family) = 0;

	virtual int Getstationid() = 0;

	virtual void Setstationid(int stationid) = 0;

	virtual int Getbayid() = 0;

	virtual void Setbayid(int bayid) = 0;

	virtual int Getequipid() = 0;

	virtual void Setequipid(int equipid) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Getmeasclassid() = 0;

	virtual void Setmeasclassid(int measclassid) = 0;

	virtual int Getdatatransflag() = 0;

	virtual void Setdatatransflag(int datatransflag) = 0;


};

#endif