/*********************************************************
 * scadalib_exprcal.h
 * contents: Iexprcal interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_exprcal_H_
#define SCADALIB_exprcal_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Itimertype;
class Icalvaluetype;
class Itimertype;
class Istation;

class Iexprcal : public IRecordSet
{
public:
	//associations
	virtual Itimertype* Relevantsavetimer() = 0;

	virtual Icalvaluetype* Relevantcalvaltype() = 0;

	virtual Itimertype* Relevantcaltimer() = 0;

	virtual Istation* Relevantstation() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getcalvaltypeid() = 0;

	virtual void Setcalvaltypeid(int calvaltypeid) = 0;

	virtual int Getcaltimerid() = 0;

	virtual void Setcaltimerid(int caltimerid) = 0;

	virtual int Getpriority() = 0;

	virtual void Setpriority(int priority) = 0;

	virtual int Getcalenable() = 0;

	virtual void Setcalenable(int calenable) = 0;

	virtual int Getsaveenable() = 0;

	virtual void Setsaveenable(int saveenable) = 0;

	virtual int Getsavetimerid() = 0;

	virtual void Setsavetimerid(int savetimerid) = 0;

	virtual string_type Getpathname() = 0;

	virtual void Setpathname(const char* pathname) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual double Getcalvalue() = 0;

	virtual void Setcalvalue(double calvalue) = 0;

	virtual dt_type Getcaltime() = 0;

	virtual void Setcaltime(dt_type caltime) = 0;

	virtual int Getquality() = 0;

	virtual void Setquality(int quality) = 0;

	virtual string_type Getfamily() = 0;

	virtual void Setfamily(const char* family) = 0;

	virtual string_type Getformula() = 0;

	virtual void Setformula(const char* formula) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Getstationid() = 0;

	virtual void Setstationid(int stationid) = 0;


};

#endif