/*********************************************************
 * scadalib_control.h
 * contents: Icontrol interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_control_H_
#define SCADALIB_control_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Icsfcommsrc;
class Itimertype;
class Imeastype;
class Iequipment;
class Imeasclass;

class Icontrol : public IRecordSet
{
public:
	//associations
	virtual Icsfcommsrc* Relevantcommsrc() = 0;

	virtual Itimertype* Relevantctrlsvtimer() = 0;

	virtual Imeastype* Relevantmeastype() = 0;

	virtual Iequipment* Relevantequip() = 0;

	virtual Imeasclass* Relevantmeasclass() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getequipid() = 0;

	virtual void Setequipid(int equipid) = 0;

	virtual int Getrelationtype() = 0;

	virtual void Setrelationtype(int relationtype) = 0;

	virtual int Getrelationid() = 0;

	virtual void Setrelationid(int relationid) = 0;

	virtual int Getmeastypeid() = 0;

	virtual void Setmeastypeid(int meastypeid) = 0;

	virtual int Getcommsrcid() = 0;

	virtual void Setcommsrcid(int commsrcid) = 0;

	virtual int Getctrlsvtimerid() = 0;

	virtual void Setctrlsvtimerid(int ctrlsvtimerid) = 0;

	virtual int Getcommpointid() = 0;

	virtual void Setcommpointid(int commpointid) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;

	virtual string_type Getpathname() = 0;

	virtual void Setpathname(const char* pathname) = 0;

	virtual string_type Getfamily() = 0;

	virtual void Setfamily(const char* family) = 0;

	virtual int Getmaxctrlcount() = 0;

	virtual void Setmaxctrlcount(int maxctrlcount) = 0;

	virtual int Getlockflag() = 0;

	virtual void Setlockflag(int lockflag) = 0;

	virtual int Getovertimelmt() = 0;

	virtual void Setovertimelmt(int overtimelmt) = 0;

	virtual int Getctrltype() = 0;

	virtual void Setctrltype(int ctrltype) = 0;

	virtual int Getctrlmode() = 0;

	virtual void Setctrlmode(int ctrlmode) = 0;

	virtual string_type Getdoublecode() = 0;

	virtual void Setdoublecode(const char* doublecode) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual int Getstationid() = 0;

	virtual void Setstationid(int stationid) = 0;

	virtual int Getbayid() = 0;

	virtual void Setbayid(int bayid) = 0;

	virtual int Getctrlcount() = 0;

	virtual void Setctrlcount(int ctrlcount) = 0;

	virtual int Getsuccount() = 0;

	virtual void Setsuccount(int succount) = 0;

	virtual dt_type Getstattime() = 0;

	virtual void Setstattime(dt_type stattime) = 0;

	virtual int Getsaveflag() = 0;

	virtual void Setsaveflag(int saveflag) = 0;

	virtual string_type Getlkexpcal() = 0;

	virtual void Setlkexpcal(const char* lkexpcal) = 0;

	virtual int Getmeasclassid() = 0;

	virtual void Setmeasclassid(int measclassid) = 0;

	virtual int Getwfflag() = 0;

	virtual void Setwfflag(int wfflag) = 0;


};

#endif