/*********************************************************
 * scadalib_station.h
 * contents: Istation interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_station_H_
#define SCADALIB_station_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Istationtype;
class Ivoltage;
class Idistrict;

class Istation : public IRecordSet
{
public:
	//associations
	virtual Istationtype* Relevantstationtype() = 0;

	virtual Ivoltage* Relevantmaxvoltage() = 0;

	virtual Idistrict* Relevantdistrict() = 0;

	//
	virtual string_type Getpathname() = 0;

	virtual void Setpathname(const char* pathname) = 0;

	virtual string_type Gettelphone() = 0;

	virtual void Settelphone(const char* telphone) = 0;

	virtual dt_type Getrundate() = 0;

	virtual void Setrundate(dt_type rundate) = 0;

	virtual int Getproflag() = 0;

	virtual void Setproflag(int proflag) = 0;

	virtual int Getwfmode() = 0;

	virtual void Setwfmode(int wfmode) = 0;

	virtual int Getwftime() = 0;

	virtual void Setwftime(int wftime) = 0;

	virtual int Getfault() = 0;

	virtual void Setfault(int fault) = 0;

	virtual int Getalarm() = 0;

	virtual void Setalarm(int alarm) = 0;

	virtual int Getgzstate() = 0;

	virtual void Setgzstate(int gzstate) = 0;

	virtual int Getdaynum() = 0;

	virtual void Setdaynum(int daynum) = 0;

	virtual dt_type Getlastdate() = 0;

	virtual void Setlastdate(dt_type lastdate) = 0;

	virtual int Getstatus() = 0;

	virtual void Setstatus(int status) = 0;

	virtual int Getlockenable() = 0;

	virtual void Setlockenable(int lockenable) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual string_type Getcommsrcid() = 0;

	virtual void Setcommsrcid(const char* commsrcid) = 0;

	virtual string_type Getalarmpage() = 0;

	virtual void Setalarmpage(const char* alarmpage) = 0;

	virtual string_type Getfamily() = 0;

	virtual void Setfamily(const char* family) = 0;

	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getdistrictid() = 0;

	virtual void Setdistrictid(int districtid) = 0;

	virtual int Getstationtypeid() = 0;

	virtual void Setstationtypeid(int stationtypeid) = 0;

	virtual int Getmaxvoltageid() = 0;

	virtual void Setmaxvoltageid(int maxvoltageid) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;


};

#endif