/*********************************************************
 * scadalib_measunit.h
 * contents: Imeasunit interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_measunit_H_
#define SCADALIB_measunit_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Imeasclass;

class Imeasunit : public IRecordSet
{
public:
	//associations
	virtual Imeasclass* Relevantmeasclass() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;

	virtual int Getmeasclassid() = 0;

	virtual void Setmeasclassid(int measclassid) = 0;


};

#endif