/*********************************************************
 * scadalib_acurvelimit.h
 * contents: Iacurvelimit interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_acurvelimit_H_
#define SCADALIB_acurvelimit_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Ialimittype;

class Iacurvelimit : public IRecordSet
{
public:
	//associations
	virtual Ialimittype* Relevantalimittype() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getalimittypeid() = 0;

	virtual void Setalimittypeid(int alimittypeid) = 0;

	virtual int Getseqno() = 0;

	virtual void Setseqno(int seqno) = 0;

	virtual dt_type Getstarttime() = 0;

	virtual void Setstarttime(dt_type starttime) = 0;

	virtual dt_type Getendtime() = 0;

	virtual void Setendtime(dt_type endtime) = 0;

	virtual double Getuppervalue() = 0;

	virtual void Setuppervalue(double uppervalue) = 0;

	virtual double Getlowervalue() = 0;

	virtual void Setlowervalue(double lowervalue) = 0;


};

#endif