/*********************************************************
 * scadalib_alarmemail.h
 * contents: Ialarmemail interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_alarmemail_H_
#define SCADALIB_alarmemail_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Ialarm;
class Imsgemail;

class Ialarmemail : public IRecordSet
{
public:
	//associations
	virtual Ialarm* Relevantalarm() = 0;

	virtual Imsgemail* Relevantmsgemail() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getalarmid() = 0;

	virtual void Setalarmid(int alarmid) = 0;

	virtual int Getmsgemailid() = 0;

	virtual void Setmsgemailid(int msgemailid) = 0;


};

#endif