/*********************************************************
 * scadalib_toponode.h
 * contents: Itoponode interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_toponode_H_
#define SCADALIB_toponode_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Itopoisland;

class Itoponode : public IRecordSet
{
public:
	//associations
	virtual Itopoisland* Relevanttopoisland() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Gettopoislandid() = 0;

	virtual void Settopoislandid(int topoislandid) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getinnerno() = 0;

	virtual void Setinnerno(int innerno) = 0;

	virtual int Getnodetype() = 0;

	virtual void Setnodetype(int nodetype) = 0;


};

#endif