/*********************************************************
 * scadalib_meastype.h
 * contents: Imeastype interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_meastype_H_
#define SCADALIB_meastype_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Imeasclass;
class Imeastype;

class Imeastype : public IRecordSet
{
public:
	//associations
	virtual Imeasclass* Relevantmeasclass() = 0;

	virtual Imeastype* Relevantctrlmtype() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getmeasclassid() = 0;

	virtual void Setmeasclassid(int measclassid) = 0;
	
	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getcode() = 0;

	virtual void Setcode(const char* code) = 0;
	
	virtual int Getctrlmtypeid() = 0;
	
	virtual void Setctrlmtypeid(int ctrlmtypeid) = 0;
	
	virtual int Getfaultflag() = 0;

	virtual void Setfaultflag(int faultflag) = 0;

	virtual int Getrelativeobj() = 0;

	virtual void Setrelativeobj(int relativeobj) = 0;

	virtual int Getequipstatusflag() = 0;

	virtual void Setequipstatusflag(int equipstatusflag) = 0;

	virtual int Getytaimvalcoff() = 0;

	virtual void Setytaimvalcoff(int ytaimvalcoff) = 0;

	virtual int Getytaimvalint() = 0;

	virtual void Setytaimvalint(int ytaimvalint) = 0;

	virtual int Getytvalchangflag() = 0;

	virtual void Setytvalchangflag(int ytvalchangflag) = 0;


};

#endif