/*********************************************************
 * scadalib_period.h
 * contents: Iperiod interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_period_H_
#define SCADALIB_period_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Iperiodtype;

class Iperiod : public IRecordSet
{
public:
	//associations
	virtual Iperiodtype* Relevantperiodtype() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getperiodtypeid() = 0;

	virtual void Setperiodtypeid(int periodtypeid) = 0;

	virtual dt_type Getstarttime() = 0;

	virtual void Setstarttime(dt_type starttime) = 0;

	virtual dt_type Getendtime() = 0;

	virtual void Setendtime(dt_type endtime) = 0;


};

#endif