/*********************************************************
 * scadalib_topoisland.h
 * contents: Itopoisland interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_topoisland_H_
#define SCADALIB_topoisland_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"



class Itopoisland : public IRecordSet
{
public:
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual int Getlinesum() = 0;

	virtual void Setlinesum(int linesum) = 0;

	virtual int Getnodesum() = 0;

	virtual void Setnodesum(int nodesum) = 0;

	virtual int Getpowersum() = 0;

	virtual void Setpowersum(int powersum) = 0;

	virtual int Getloadsum() = 0;

	virtual void Setloadsum(int loadsum) = 0;

	virtual int Getgroundsum() = 0;

	virtual void Setgroundsum(int groundsum) = 0;

	virtual int Getactivefflag() = 0;

	virtual void Setactivefflag(int activefflag) = 0;


};

#endif