/*********************************************************
 * scadalib_alarmclass.h
 * contents: Ialarmclass interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_alarmclass_H_
#define SCADALIB_alarmclass_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Iapp;

class Ialarmclass : public IRecordSet
{
public:
	//associations
	virtual Iapp* Relevantapp() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getappid() = 0;

	virtual void Setappid(int appid) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;


};

#endif