/*********************************************************
 * scadalib_settingenum.h
 * contents: Isettingenum interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_settingenum_H_
#define SCADALIB_settingenum_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"



class Isettingenum : public IRecordSet
{
public:
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual string_type Getvalue() = 0;

	virtual void Setvalue(const char* value) = 0;

	virtual string_type Getdescription() = 0;

	virtual void Setdescription(const char* description) = 0;

	virtual string_type Getname() = 0;

	virtual void Setname(const char* name) = 0;


};

#endif