/*********************************************************
 * scadalib_alarmphone.h
 * contents: Ialarmphone interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_alarmphone_H_
#define SCADALIB_alarmphone_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Ialarm;
class Imsgphone;

class Ialarmphone : public IRecordSet
{
public:
	//associations
	virtual Ialarm* Relevantalarm() = 0;

	virtual Imsgphone* Relevantmsgphone() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getmsgphoneid() = 0;

	virtual void Setmsgphoneid(int msgphoneid) = 0;

	virtual int Getalarmid() = 0;

	virtual void Setalarmid(int alarmid) = 0;


};

#endif