/*********************************************************
 * scadalib_ctrlexp.h
 * contents: Ictrlexp interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_ctrlexp_H_
#define SCADALIB_ctrlexp_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Icontrol;
class Ictrlvaltype;

class Ictrlexp : public IRecordSet
{
public:
	//associations
	virtual Icontrol* Relevantcontrol() = 0;

	virtual Ictrlvaltype* Relevantctrlvaltype() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getctrlvaltypeid() = 0;

	virtual void Setctrlvaltypeid(int ctrlvaltypeid) = 0;

	virtual int Getcontrolid() = 0;

	virtual void Setcontrolid(int controlid) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;

	virtual string_type Getopexprcal() = 0;

	virtual void Setopexprcal(const char* opexprcal) = 0;


};

#endif