/*********************************************************
 * scadalib_accumulsrc.h
 * contents: Iaccumulsrc interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_accumulsrc_H_
#define SCADALIB_accumulsrc_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Icsfcommsrc;
class Iaccumulator;

class Iaccumulsrc : public IRecordSet
{
public:
	//associations
	virtual Icsfcommsrc* Relevantcommsrc() = 0;

	virtual Iaccumulator* Relevantaccumulator() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getaccumulatorid() = 0;

	virtual void Setaccumulatorid(int accumulatorid) = 0;

	virtual int Getcommsrcid() = 0;

	virtual void Setcommsrcid(int commsrcid) = 0;

	virtual int Getcommpointid() = 0;

	virtual void Setcommpointid(int commpointid) = 0;

	virtual int Getpriority() = 0;

	virtual void Setpriority(int priority) = 0;

	virtual double Getrawvalue() = 0;

	virtual void Setrawvalue(double rawvalue) = 0;

	virtual dt_type Getrawvaluetime() = 0;

	virtual void Setrawvaluetime(dt_type rawvaluetime) = 0;

	virtual int Getquality() = 0;

	virtual void Setquality(int quality) = 0;

	virtual int Getdeleteflag() = 0;

	virtual void Setdeleteflag(int deleteflag) = 0;


};

#endif