/*********************************************************
 * scadalib_alarmgroup.h
 * contents: Ialarmgroup interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_alarmgroup_H_
#define SCADALIB_alarmgroup_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Ialarm;
class Ialmgrptype;

class Ialarmgroup : public IRecordSet
{
public:
	//associations
	virtual Ialarm* Relevantalarm() = 0;

	virtual Ialmgrptype* Relevantalarmgrptype() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getalarmid() = 0;

	virtual void Setalarmid(int alarmid) = 0;

	virtual int Getalarmgrptypeid() = 0;

	virtual void Setalarmgrptypeid(int alarmgrptypeid) = 0;


};

#endif