/*********************************************************
 * scadalib_analprdlmt.h
 * contents: Ianalprdlmt interface
 * date: 2009-09-23 code generated by scadalib_gen(hongkeqin@xjgc.com)
 *********************************************************/

#ifndef SCADALIB_analprdlmt_H_
#define SCADALIB_analprdlmt_H_

#include "../icsunknown.h"
#include "./scadalib_typedef.h"
#include "./irecordset.h"


//forward declarations
class Ialimittype;
class Iperiodtype;

class Ianalprdlmt : public IRecordSet
{
public:
	//associations
	virtual Ialimittype* Relevantalimittype() = 0;

	virtual Iperiodtype* Relevantperiodtype() = 0;

	//
	virtual int Getid() = 0;

	virtual void Setid(int id) = 0;

	virtual int Getalimittypeid() = 0;

	virtual void Setalimittypeid(int alimittypeid) = 0;

	virtual int Getperiodtypeid() = 0;

	virtual void Setperiodtypeid(int periodtypeid) = 0;

	virtual double Getuppervalue() = 0;

	virtual void Setuppervalue(double uppervalue) = 0;

	virtual double Getlowervalue() = 0;

	virtual void Setlowervalue(double lowervalue) = 0;


};

#endif